config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  devise_for :users

  devise_scope :user do
    authenticated do
      root to: 'home#index'
    end
    unauthenticated do
      root to: 'devise/sessions#new', as: 'unauthenticated_root'
    end
  end

  get 'home', to: 'home#index'

  resources :likes, only: %i[create destroy]
  resources :reports, only: %i[index create destroy]
  resources :suggestions, only: %i[create new index destroy]

  resources :posts do
    resource :comments, only: %i[create destroy new] do
      member do
        put 'like', to: 'comments#vote'
      end
    end
    member do
      put 'like', to: 'posts#vote'
      patch :publish, as: 'publish'
      patch :unpublish, as: 'unpublish'
    end
  end
end

app/models/comment.rb
# frozen_string_literal: true

class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :post
  belongs_to :parent, class_name: 'Comment', optional: true
  has_many :replies, class_name: 'Comment', foreign_key: :parent_id, dependent: :destroy
  has_one_attached :image, dependent: :destroy
  has_many :reports, as: :reportable, dependent: :destroy
  acts_as_votable

  validates :body, presence: true
end

app/controllers/comments_controller.rb
# frozen_string_literal: true

# comments controller
class CommentsController < ApplicationController
  before_action :set_comment, only: %i[update destroy vote]
  before_action :set_post, only: %i[new create]

  def new
    @comment = Comment.new
    authorize @comment
  end

  def create
    authorize Comment
    @comment = @post.comments.new(comment_params)
    @comment.save
  end

  def destroy
    @comment = Comment.find_by(id: params[:post_id])
    @comment.destroy
  end

  def vote
    if !current_user.liked? @comment
      @comment.liked_by current_user
    elsif current_user.liked? @comment
      @comment.unliked_by current_user
    end
  end

  private

  def set_post
    @post = Post.find(params[:post_id])
  end

  def set_comment
    @comment = Comment.find_by(id: params[:post_id])
    authorize @comment
  end

  def comment_params
    params.require(:comment).permit(:body, :parent_id, :image, :user_id)
  end
end

app/helpers/comment_helper.rb
# frozen_string_literal: true

# helper for like controller
module CommentHelper
  def get_name_from_email(email)
    email.split('@').first
  end
end

app/views/comments/_all_comment.html.erb
<% comments.where(parent_id: nil).each do |comment| %>
    <%= render partial: '/comments/comment' , locals: {comment: comment} %>
<%end%>
<hr>

app/views/comments/_comment.html.erb
<div id='comment'></div>
<div id="deleteComment<%=comment.id%>">
  <div class="card ml-5 mr-5 mb-2">
    <div class="card-body text-secondary">

      <%= render partial: '/shared/person_avatar'%><strong><%= get_name_from_email(comment.user.email) %></strong>
      <%= comment.body %>
      <%if comment.image.attached?%>
        <p>
          <%= image_tag comment.image, style: "width: 200px; display: block"%>
        </p>
      <%end%>
      <% if current_user.user?%>
        <%= render partial: '/reports/report_unreport', locals: {post: comment, type: 'Comment'}%>
      <%end%>
      <%if comment.parent_id.nil?%>
        <%= link_to like_post_comments_path(comment), class: "comment-like-btn", method: :put, remote: true do %>
            <span><i class='fa fa-thumbs-up fa-1x'></i></span>
        <%end%>
        <div class='float-right'>Likes:<span class="comment-likes-count-<%=comment.id%>"><%= comment.get_upvotes.size%></span></div>
      <%end%>
        <div id='reply'>
        <% if comment.replies.any?%>
          <% comment.replies.each do |reply|%>
              <div id="deleteComment<%=reply.id%>">
                <div id='reply'></div>
                <div class="card ml-5 mt-3">
                  <div class="card-body">
                        <%= render partial: '/shared/person_avatar'%><strong><%= get_name_from_email(reply.user.email) %></strong>
                        <%=reply.body%>
                        <% if current_user.user?%>
                          <%= render partial: '/reports/report_unreport', locals: {post: reply, type: 'Comment'}%>
                        <%end%>

                        <%if reply.user_id == current_user.id or  !current_user.user?%>
                          <%= render partial: '/shared/delete_button' , locals: {post: post_comments_path(reply.id)}%>
                        <%end%>
                  </div>
                </div>
              </div>
          <%end%>
        <%end%>
        </div>
        <div class='commentform'>
          <%if comment.parent_id.nil?%>
            <%= render partial: '/comments/comment_form' , locals: {parent: comment, id: 'rply-form'}%>
          <%end%>
        </div>
        <%if comment.user_id == current_user.id or  !current_user.user?%>
            <%= render partial: '/shared/delete_button' , locals: {post: post_comments_path(comment.id)}%>
        <%end%>
    </div>
  </div>
</div>

app/views/comments/_comment_block.html.erb
<div class="card m-3 bg-light">
  <div class="card-body">
    <p class="font-weight-bold">Comments</p>
    <div id='first-comment'></div>
    <%= render partial: '/comments/all_comment' , locals: {comments: @post.comments} %>
    <%= render partial: '/comments/comment_form' , locals: {parent: nil}%>
  </div>
</div>

app/views/comments/_comment_form.html.erb
<%= form_with(model: [@post, @post.comments.build], validate: true) do |f| %>
      <div class="form-group">
          <% if !parent.nil?%>
          <input type='hidden' name="comment[parent_id]" value="<%= parent.id%>" >
          <%end%>
          <%if parent.nil?%>
            <%= f.label 'New comment' , class: 'font-weight-bold'%>
            <input type='hidden' name="comment[user_id]" value="<%= current_user.id%>" >
            <%= f.text_area :body, required: true, class: 'form-control' %>
            <%= f.file_field :image, class: 'form-control' %>
            <%= f.submit 'Comment', class: 'btn btn-dark mt-2' , id: 'c-btn' %>
          <%else%>
            <input type='hidden' name="comment[user_id]" value="<%= current_user.id%>" >
            <%= f.text_area :body, required: true, class: 'form-control mt-2 ', id:id%>
            <%= f.submit 'Reply', class: 'btn btn-dark mt-2' %>
          <%end%>
      </div>
<% end %>

app/views/comments/create.js.erb
  <%if !@comment.parent_id%>
    $('#first-comment').append("<%= j render partial: 'comment', locals: {comment: @comment}%>");
    tf = document.getElementById('comment_body')
    tf.value = ""
  <%else%>
      $('#reply').append("<%= j render partial: 'comment', locals: {comment: @comment, parent: @comment}%>");
      tf = document.getElementById('rply-form')
      tf.value = ""
  <%end%>

app/views/comments/destroy.js.erb
let delete<%=@comment.id%> = document.querySelector("#deleteComment"+<%=@comment.id%>);
delete<%=@comment.id%>.remove();

app/views/comments/new.html.erb
    <%= render partial: '/comments/comment_form' , locals: {post: @post} %>

app/views/comments/vote.js.erb
<%if @comment.parent_id.nil? %>
  <%if current_user.liked? @comment%>
    $('.comment-like-btn-<%=@comment.id%>').addClass('liked');
  <%else%>
    $('.comment-like-btn-<%=@comment.id%>').addClass('like-btn');
  <%end%>
  $('.comment-likes-count-<%=@comment.id%>').html("<%= @comment.get_upvotes.size%>")
<%elsif !@comment.parent_id.nil? %>
    <%if current_user.liked? @comment%>
    $('.reply-like-btn').addClass('liked');
  <%else%>
    $('.reply-like-btn').addClass('like-btn');
  <%end%>
  $('.reply-likes-count').html("<%= @comment.get_upvotes.size%>")
<%end%>