config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  devise_for :users

  devise_scope :user do
    authenticated do
      root to: 'home#index'
    end
    unauthenticated do
      root to: 'devise/sessions#new', as: 'unauthenticated_root'
    end
  end

  get 'home', to: 'home#index'

  resources :likes, only: %i[create destroy]
  resources :reports, only: %i[index create destroy]
  resources :suggestions, only: %i[create new index destroy]

  resources :posts do
    resource :comments, only: %i[create destroy new] do
      member do
        put 'like', to: 'comments#vote'
      end
    end
    member do
      put 'like', to: 'posts#vote'
      patch :publish, as: 'publish'
      patch :unpublish, as: 'unpublish'
    end
  end
end

app/views/shared/_background_img.html.erb
<img src="https://images.unsplash.com/photo-1471107340929-a87cd0f5b5f3?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1673&q=80
" class="img-fluid"  alt="Responsive image">

app/views/shared/_below_image_tag.html.erb
<div class='container'>
  <h1 class="page-header pt-7">
    <%if tag[:allposts]%>
        <%if !current_user.user?%>
                <span>All Posts</span>
        <%else%>
                <span>Your All Posts</span>
        <%end%>
    <%end%>
  </h1>
</div>

app/views/shared/_delete_button.html.erb
  <%= link_to  post, method: :delete, remote: true , data: { confirm: 'Are you sure to Delete?' }, class: 'text-secondary mt-2 mr-2' do %>
      <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-trash" viewBox="0 0 16 16">
        <path d="M5.5 5.5A.5.5 0 0 1 6 6v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5zm2.5 0a.5.5 0 0 1 .5.5v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5zm3 .5a.5.5 0 0 0-1 0v6a.5.5 0 0 0 1 0V6z"/>
        <path fill-rule="evenodd" d="M14.5 3a1 1 0 0 1-1 1H13v9a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V4h-.5a1 1 0 0 1-1-1V2a1 1 0 0 1 1-1H6a1 1 0 0 1 1-1h2a1 1 0 0 1 1 1h3.5a1 1 0 0 1 1 1v1zM4.118 4 4 4.059V13a1 1 0 0 0 1 1h6a1 1 0 0 0 1-1V4.059L11.882 4H4.118zM2.5 3V2h11v1h-11z"/>
      </svg>
  <%end%>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-sm bg-dark navbar-dark fixed-top shadow">
  <%if current_user%>
    <%= link_to "Blogger", home_path, class: 'navbar-brand'%>

    <ul class="navbar-nav">
      <li class="nav-item">
        <%= link_to "Allposts", posts_path(allposts: true), class: 'nav-link'%>
      </li>

      <%if current_user.user?%>
        <li class="nav-item">
          <%= link_to "Suggestions", suggestions_path , class: 'nav-link'%>
        </li>
        <li class="nav-item mr-2">
          <%= link_to 'New Post', new_post_path , class: 'btn btn-success'%>
        </li>
      <%else%>
        <li class="nav-item">
          <%= link_to "Reported", reports_path, class: 'nav-link'%>
        </li>
      <%end%>
      <li class="nav-item ">
        <%= link_to 'Sign out', destroy_user_session_path , method: :delete , class: 'btn btn-secondary'%>
      </li>

      <li class="nav-item float-right justify-content-end">
        <%= link_to 'Edit Profile', edit_user_registration_path,  class: 'nav-link'%>
      </li>

    </ul>
  <%else%>
    <a class="navbar-brand" href="#">Blogger</a>
  <%end%>
</nav>

app/views/shared/_person_avatar.html.erb
<img src="https://cdn-icons-png.flaticon.com/512/3177/3177440.png" alt="Avatar" class="avatar">