config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  devise_for :users

  devise_scope :user do
    authenticated do
      root to: 'home#index'
    end
    unauthenticated do
      root to: 'devise/sessions#new', as: 'unauthenticated_root'
    end
  end

  get 'home', to: 'home#index'

  resources :likes, only: %i[create destroy]
  resources :reports, only: %i[index create destroy]
  resources :suggestions, only: %i[create new index destroy]

  resources :posts do
    resource :comments, only: %i[create destroy new] do
      member do
        put 'like', to: 'comments#vote'
      end
    end
    member do
      put 'like', to: 'posts#vote'
      patch :publish, as: 'publish'
      patch :unpublish, as: 'unpublish'
    end
  end
end

app/models/post.rb
# frozen_string_literal: true

# main post model
class Post < ApplicationRecord
  include Hashid::Rails

  belongs_to :user
  has_rich_text :content
  acts_as_votable
  has_many :comments, dependent: :destroy
  has_many :reports, as: :reportable, dependent: :destroy
  has_many :suggestions, dependent: :destroy

  validates :title, :description, :content, presence: true
  validates :title, length: { in: 5..60 }
  validates :description, length: { in: 15..100 }
  validates :content, length: { minimum: 25 }

  # methods for post controllers

  def self.get_ordered_posts(user)
    if !user.user?
      Post.all.order({ published: :asc, created_at: :desc })
    else
      user.posts.all.order({ published: :asc, created_at: :desc })
    end
  end
end

app/controllers/posts_controller.rb
# frozen_string_literal: true

# PostController with crud actions
class PostsController < ApplicationController
  before_action :set_post, only: %i[show edit update destroy publish unpublish vote]
  after_action :verify_authorized, except: :index
  after_action :verify_policy_scoped, only: :idex

  def index
    @post_type = params
    @pagy, @posts = pagy(
      (Post.get_ordered_posts(current_user) if params[:allposts]))
  end

  def show; end

  def new
    @post = current_user.posts.build
    authorize @post
  end

  def edit; end

  def create
    @post = current_user.posts.build(post_params)
    authorize @post

    respond_to do |format|
      if @post.save
        format.html { redirect_to home_path, notice: t('.notice') }
      else
        format.html { redirect_to home_path, alert: t('.alert') }
      end
    end
  end

  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to home_path, notice: t('.notice') }
      else
        format.html { redirect_to home_path, alert: t('.alert')  }
      end
    end
  end

  def publish
    respond_to do |format|
      if @post.update(published: true)
        format.html { redirect_to post_path(@post), notice: t('.notice') }
      else
        format.html { redirect_to post_path(@post), alert: t('.alert') }
      end
    end
  end

  def unpublish
    respond_to do |format|
      if @post.update(published: false)
        format.html { redirect_to post_path(@post), notice: t('.notice') }
      else
        format.html { redirect_to post_path(@post), alert: t('.alert') }
      end
    end
  end

  def vote
    if !current_user.liked? @post
      @post.liked_by current_user
    elsif current_user.liked? @post
      @post.unliked_by current_user
    end
  end

  def destroy
    @post.destroy
  end

  private

  def set_post
    @post = Post.find(params[:id])
    authorize @post
  end

  def post_params
    params.require(:post).permit(:title, :content, :description)
  end
end

app/helpers/post_helper.rb
# frozen_string_literal: true

# helper for like controller
module PostHelper
  def published?(post)
    post.published?
  end
end

app/views/posts/_all_posts.html.erb
<table>
  <thead>
    <tr>
      <%= render partial: '/shared/below_image_tag', locals: {tag: post_type}%>
  </thead>

  <tbody>
    <% if !@posts.nil?%>
      <% @posts.each do |post| %>
          <%= render partial: '/posts/post_body', locals: {post: post}%>
      <%end %>
    <%else%>
      <h1>Bad Request</h1>
    <%end%>
  </tbody>
</table>

app/views/posts/_form.html.erb
<%= form_with(model: post, local: true, validate: true) do |form| %>
  <% if post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class=" field ">
    <h5><%= form.label :title %></h5>
    <%= form.text_field :title, required: true , class: 'form-control'%>

    <h5><%= form.label :description , class: 'mt-3 mb-3'%></h5>
    <%= form.text_area :description, required: true, class: 'form-control'%>

    <h5><%= form.label :content, class: 'mt-3 mb-3'%></h5>
    <%= form.rich_text_area :content, required: true, id: :post_body%>

    <div class="actions mt-3 ">
      <%= form.submit 'Submit' , class: 'btn btn-success' %>
    </div>
  </div>
<% end %>

app/views/posts/_post_body.html.erb
<div id="deletePost<%=post.id%>">
  <div class='jumbotron container mt-3 p-1 shadow' >
      <div class="card-title d-flex justify-content-between">
        <%if post.published?%>
            <div class = "badge badge-success text-white ml-3 mr-3 mt-3"><span>Published </span></div>
        <%else%>
            <div class = "badge badge-primary text-white ml-3 mr-3 mt-3"><span>Not Published </span></div>
        <%end%>

        <%if post.user_id == current_user.id or  !current_user.user?%>
            <%= render partial: '/shared/delete_button' , locals: {post: post}%>
        <%end%>

      </div>


      <div class="card-body">
        <div class="card-title d-flex justify-content-between"><h4><%= post.title.capitalize %></h4>
        </div>
        <div class="card-text"><%= post.description.truncate(200) %></div>
          <%if post.published%>
            <div class="card-text text-secondary"><span >Likes:</span><span class='likes-count'><%= post.get_upvotes.size%></span></div>
            <%if !post.comments.first.nil?%>
              <div class="card-text text-secondary"><span >Recent Comment :</span> "<%= post.comments.order('created_at DESC').first.body%>"</div>
            <%end%>
          <%end%>
          <%if current_user.user? %>
            <%if post.user_id == current_user.id or !current_user.user?%>
              <div class= 'btn-group'>
                <%= link_to 'Show', post , class: 'card-link text-decoration-none btn btn-dark mt-2' %>
                <%= link_to 'Edit', edit_post_path(post),class: 'card-link text-decoration-none btn btn-secondary  mt-2' %>
              </div>
            <%else%>
              <div class="card-title d-flex justify-content-between">
                  <div><%= link_to 'Show', post , class: 'card-link text-decoration-none btn btn-dark mt-2' %></div>
              </div>
            <%end%>

          <%else%>
            <div class="card-text text-secondary"><span ><%= post.user.role %>:</span><%= post.user.email %></div>
            <div class= 'btn-group'>
                <%= link_to 'Show', post , class: 'card-link text-decoration-none btn btn-dark mt-2' %>
            </div>
            <br>
          <%end%>
      </div>
  </div>
</div>

app/views/posts/_post_image.html.erb
<img src="https://images.unsplash.com/photo-1592819695396-064b9572a660?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=2070&q=80
" class="img-fluid shadow" id='post-img' alt="Responsive image">

app/views/posts/destroy.js.erb
let delete<%=@post.id%> = document.querySelector("#deletePost"+<%=@post.id%>);
delete<%=@post.id%>.remove();

app/views/posts/edit.html.erb
<div class = 'row'>
  <div class = col-md-12  >
    <div class= 'card m-3'>
      <div class = 'card-body'>
        <h3 class = 'card-title mb-4'>Edit Post</h3>
        <%= render '/posts/form', post: @post %>
      </div>
    </div>
  </div>

</div>

app/views/posts/index.html.erb
<%= render partial: '/posts/post_image'%>

<%= render partial: '/posts/all_posts' , locals: {posts: @posts, post_type: @post_type}%>
<div class= 'pl-70 '>
    <%= raw pagy_bootstrap_nav(@pagy)%>
<div>

app/views/posts/new.html.erb
<div class = 'row'>
  <div class = col-md-12  >
    <div class= 'card m-3'>
      <div class = 'card-body'>
        <h3 class = 'card-title mb-4'>New Post</h3>
        <%= render '/posts/form', post: @post %>
      </div>
    </div>
  </div>
</div>

app/views/posts/show.html.erb
<div class=' m-3 d-flex justify-content-between'>
    <%if !current_user.user? %>
      <%if  published?(@post) %>
        <div >
          <%= link_to 'Unpublish', unpublish_post_path(@post) , method: :patch, remote: true ,class: 'card-link text-decoration-none btn btn-danger ' %>
        </div>
      <%else%>
        <div>
          <%= link_to 'Publish', publish_post_path(@post) , method: :patch , remote: true ,class: 'card-link text-decoration-none btn btn-success ' %>
        </div>
      <%end%>
    <%end%>
</div>

<div class = 'row '>
  <div class = col-md-12  >
    <div class= 'card m-3'>
      <div class = 'card-body'>
        <div class="card-title d-flex justify-content-between">
          <h3 class = 'card-title mb-4'><%= @post.title %></h3>
          <%= link_to like_post_path(@post), class: 'like-btn', method: :put, remote: true do %>
            <div >
              <span><i class='fa fa-thumbs-up fa-2x'></i></span>
              Likes:<span class='likes-count'><%= @post.get_upvotes.size%></span>
            </div>
          <%end%>
        </div>
        <p class= 'card-text text-secondary'>
          <strong>Created By:</strong>
          <%= @post.user.email %>
        </p>
        <p class= 'card-text'>
          <strong>Description:</strong>
          <%= @post.description %>
          <%= @post.content %>
        </p>
      </div>
      <div class=' m-3 d-flex justify-content-between'>
        <%if current_user.user?%>
          <%if published?(@post)%>
            <%= render partial: '/reports/report_unreport', locals: {post: @post, type: 'Post'}%>
          <%end%>
        <%end%>
        <div>
          <% if published?(@post)%>
            <%= link_to 'Suggestions?', new_suggestion_path(id: @post.id)  %>
          <%end%>
        </div>
      </div>
    </div>
  </div>
</div>
<%if @post.published%>
  <%= render partial: '/comments/comment_block' , local: {post: @post, parent: nil}%>
<%end%>

app/views/posts/vote.js.erb
<%if current_user.liked? @post%>
  $('.like-btn').addClass('liked');
<%else%>
  $('.like-btn').addClass('like-btn');
<%end%>
$('.likes-count').html("<%= @post.get_upvotes.size%>")