config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  devise_for :users

  devise_scope :user do
    authenticated do
      root to: 'home#index'
    end
    unauthenticated do
      root to: 'devise/sessions#new', as: 'unauthenticated_root'
    end
  end

  get 'home', to: 'home#index'

  resources :likes, only: %i[create destroy]
  resources :reports, only: %i[index create destroy]
  resources :suggestions, only: %i[create new index destroy]

  resources :posts do
    resource :comments, only: %i[create destroy new] do
      member do
        put 'like', to: 'comments#vote'
      end
    end
    member do
      put 'like', to: 'posts#vote'
      patch :publish, as: 'publish'
      patch :unpublish, as: 'unpublish'
    end
  end
end

app/models/report.rb
# frozen_string_literal: true

class Report < ApplicationRecord
  belongs_to :user
  belongs_to :reportable, polymorphic: true

  validates :user_id, uniqueness: { scope: %i[reportable_id reportable_type] }

  # scopes for report controller
  scope :destroy_report, ->(user, params) { user.reports.find_by(reportable_id: params[:id]) }
end

app/controllers/reports_controller.rb
# frozen_string_literal: true

# report controller
class ReportsController < ApplicationController
  def create
    authorize Report

    @report = current_user.reports.new(report_params)
    respond_to do |format|
      if @report.save
        format.html { redirect_back(fallback_location: posts_url, notice: t('.notice')) }
      else
        format.html { redirect_to home_path, alert: t('.alert') }
      end
    end
  end

  def index
    @reports = Report.all
  end

  def destroy
    @report = Report.destroy_report(current_user, params)
    authorize @report
    respond_to do |format|
      if @report.destroy
        format.html { redirect_back(fallback_location: posts_url, notice: t('.notice')) }
      else
        format.html { redirect_to home_path, alert: t('.alert') }
      end
    end
  end

  private

  def report_params
    params.permit(:reportable_id, :reportable_type)
  end
end

app/helpers/report_helper.rb
# frozen_string_literal: true

# helper for like controller
module ReportHelper
  def reported?(user, post, type)
    Report.where(user_id: user.id, reportable_id: post.id, reportable_type: type).exists?
  end
end

app/views/reports/_report_icon.html.erb
<svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-question-circle-fill" viewBox="0 0 16 16">
  <path d="M16 8A8 8 0 1 1 0 8a8 8 0 0 1 16 0zM5.496 6.033h.825c.138 0 .248-.113.266-.25.09-.656.54-1.134 1.342-1.134.686 0 1.314.343 1.314 1.168 0 .635-.374.927-.965 1.371-.673.489-1.206 1.06-1.168 1.987l.003.217a.25.25 0 0 0 .25.246h.811a.25.25 0 0 0 .25-.25v-.105c0-.718.273-.927 1.01-1.486.609-.463 1.244-.977 1.244-2.056 0-1.511-1.276-2.241-2.673-2.241-1.267 0-2.655.59-2.75 2.286a.237.237 0 0 0 .241.247zm2.325 6.443c.61 0 1.029-.394 1.029-.927 0-.552-.42-.94-1.029-.94-.584 0-1.009.388-1.009.94 0 .533.425.927 1.01.927z"/>
</svg>

app/views/reports/_report_unreport.html.erb
  <%if reported?(current_user, post, type)%>
    <%= link_to report_path(post.id), method: :delete, remote: true, data: { confirm: 'Are you sure to unreport?' } , class: 'card-link text-decoration-none ' do%>
      Reported<%= render partial: '/reports/report_icon'%>
    <%end%>

  <%else%>
    <%= link_to  reports_path(reportable_id: post.id, reportable_type: type), data: { confirm: 'Are you sure to Report?' } , method: :post, remote: true, class: 'card-link text-decoration-none ' do%>
      Report<%= render partial: '/reports/unreport_icon'%>
    <%end%>
  <%end%>

app/views/reports/_unreport_icon.html.erb
<svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-question-circle" viewBox="0 0 16 16">
  <path d="M8 15A7 7 0 1 1 8 1a7 7 0 0 1 0 14zm0 1A8 8 0 1 0 8 0a8 8 0 0 0 0 16z"/>
  <path d="M5.255 5.786a.237.237 0 0 0 .241.247h.825c.138 0 .248-.113.266-.25.09-.656.54-1.134 1.342-1.134.686 0 1.314.343 1.314 1.168 0 .635-.374.927-.965 1.371-.673.489-1.206 1.06-1.168 1.987l.003.217a.25.25 0 0 0 .25.246h.811a.25.25 0 0 0 .25-.25v-.105c0-.718.273-.927 1.01-1.486.609-.463 1.244-.977 1.244-2.056 0-1.511-1.276-2.241-2.673-2.241-1.267 0-2.655.59-2.75 2.286zm1.557 5.763c0 .533.425.927 1.01.927.609 0 1.028-.394 1.028-.927 0-.552-.42-.94-1.029-.94-.584 0-1.009.388-1.009.94z"/>
</svg>

app/views/reports/index.html.erb
</table>
<table class="table table-striped">
  <thead>
    <tr>
      <th scope="col">#</th>
      <th scope="col">Report item</th>
      <th scope="col">Title</th>
      <th scope="col">Reported by</th>
    </tr>
  </thead>
  <tbody>
    <% @reports.each do |data| %>
      <tr>
        <th scope="row"></th>
        <td><%= data.reportable_type %></td>
        <%if data.reportable_type == 'Post'%>
          <td>
          <%= link_to post_path(data.reportable_id) do%>
            <%= Post.find_by(id: data.reportable_id).title %></td>
          <%end%>
        <%else%>
        <td>
          <%= link_to post_path(Comment.find_by(id: data.reportable_id).post_id) do%>
            <%= Comment.find_by(id: data.reportable_id).body%></td>
          <%end%>
        <%end%>
        <td><%= data.user.email %></td>
      </tr>
     <%end%>
  </tbody>
</table>